<div class ="content">
<? $base = $this->linkTo('self');  
 $xsl_opts = array('mode' => "poem");
if (isset($this->self)) $xsl_opts["selflink"] = $this->self;
if (isset($this->base)) $xsl_opts["base"] = $this->base; ?>
<? if (preg_match("/poem/i", $this->poem->type)): ?><div class="poem">
<? else :?><div class="essay"><? endif ?>
      
    <?= $this->xslTransform($this->poem->text->saveXML(), "poetry.xsl", $xsl_opts); ?>
    </div>
<p class="source">
  from <a href="<?= $this->url(array('action' => "content", 'id' => $this->poem->docname . '.xml'), null) ?>"><?= $this->poem->title ?></a><? if (isset($this->poem->author) && $this->poem->author): ?>, <?= $this->poem->author ?><? elseif  (isset($this->poem->editor) && $this->poem->editor): ?>, <?= $this->poem->editor ?><? endif ?></p>

<p class="next-prev">
    Continue browsing this volume:<br/>
    <? if ($this->poem->prev): ?>
	Previous poem: <a href="<?= $this->url(array('id' => $this->poem->previd)) ?>"><?= $this->poem->prevn ?></a><? if (isset($this->poem->pdoc) && $this->poem->pdoc): ?>, <?= $this->poem->pdoc ?><? endif ?><? endif ?><br/>
    <? if ($this->poem->next): ?>
	Next poem: <a href="<?= $this->url(array('id' => $this->poem->nextid)) ?>"><?= $this->poem->nextn ?></a><? if (isset($this->poem->ndoc) && $this->poem->ndoc): ?>, <?= $this->poem->ndoc ?><? endif ?><? endif ?></p>


<p class="copyright">
    <? if (isset($this->poem->biblauth) && $this->poem->biblauth): ?><?= $this->poem->biblauth . "," ?>
   <? elseif (isset($this->poem->bibled) && $this->poem->bibled): ?><?= $this->poem->bibled . ", ed.," ?><? endif ?>
 <i><?= $this->poem->bibltitle ?><i>. <?= $this->poem->biblpubp ?>: <?= $this->poem->biblpub ?>, <?= $this->poem->bibldate ?>.
</p>
</div>

  <pre><? //print_r($this->poem) ?></pre> <!-- outputs the array; view source for xml -->