<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
   <title>The Great War: <?= $this->escape($this->title) ?></title>
   <?= $this->css('wwi.css'); ?>

</head>

<body>
<?//= $this->layout()->content ?>








  /*include_once("lib/mybreadcrumb.php");

include("header.php");
print "<p class='breadcrumbs'>" . $breadcrumb->show_breadcrumb() . "</p>";

// actual content: introductory essay (in content directory)
include("about.xml");


print '<div class="sidebar">';
include("searchbox.php");
print '</div>';
include("footer.html");*/


</body>
</html>

