<? $base = $this->linkTo('self');  
 $xsl_opts = array('mode' => "poem");
if (isset($this->self)) $xsl_opts["selflink"] = $this->self;
if (isset($this->base)) $xsl_opts["base"] = $this->base; ?>
<? if (preg_match("/poem/i", $this->poem->type)): ?><div class="poem">
<? else :?><div class="essay"><? endif ?>
      
    <?= $this->xslTransform($this->poem->text->saveXML(), "poetry.xsl", $xsl_opts); ?>
    </div>




  <pre><? //print_r($this->poem) ?></pre> <!-- outputs the array; view source for xml -->