<div class="poem">
<p class="head"><?= $this->poem->n ?></p>
   <p class="subhead"><? if (isset($this->poem->docAuthor) && $this->poem->docAuthor): ?><?= $this->poem->docAuthor ?>
   <? endif ?>
</p>
   
	  <? foreach ($this->poem->lg as $group): ?><p>
		<? $this->partial("poetry/_poem_line.phtml", array("group" => $group)) ?>
											  <?// endforeach ?>
          </p><? endforeach ?>

 <? if (isset($this->poem->byline) && $this->poem->byline): ?><p class="byline"><?= $this->poem->byline ?></p><? endif ?>
</div>
											  <pre><? //print_r($this->poem) ?></pre> <!-- outputs the array; view source for xml -->