<?= $this->img("images/topbanner.jpg", array('alt' => 'The Great War top image', 'width' => '800', 'height' => '90', 'borders' => '0' )) ?>
<table width="700" border='0' cellpadding='0' cellspacing='0' >
<tr>
     <td class="navlink"><a href="<?= $this->url(array("controller" => "index", "action" => "index"), null, true) ?>" >Home</a></td>
     <td class="separator">&bull;</td>
     <td class="navlink"><a href="<?= $this->url(array("controller" => "postcards"), null, true) ?>">Postcards</a></td>
     <td class="separator">&bull;</td>
     <td class="navlink"><a href="<?= $this->url(array("controller" => "poetry", "action" => "index"), null, true) ?>">Poetry</a></td>
     <td class="separator">&bull;</td>
     <td class="navlink"><a href="<?= $this->url(array("controller" => "links"), null, true) ?>">Links</a></td>
     <td class="separator">&bull;</td>
     <td class="navlink"><a href="<?= $this->url(array("controller" => "index", "action" => "about"), null, true) ?>">About the Site</a></td>
     <td class="separator">&bull;</td>
     <td class="navlink"><a href="<?= $this->url(array("controller" => "index", "action" => "credits"), null, true) ?>">Credits</a></td>
</tr>

</table>
<hr align="left"/>