<!DOCTYPE html PUBLIC "-//W3C/DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <?= $this->css('wwi.css'); ?>
<style type="text/css">
a:link	  { color: #000000; }
a:active  { color: #687c54; } 
a:visited { color: #b52512; }
a:hover   { background-color: #ededed; }
body { text-align: center; }
</style>
  <link rel="schema.DC" href="http://purl.org/dc/elements/1.1/"/>
  <link rel="schema.DCTERMS" href="http://purl.org/dc/terms/"/>
  <meta name="DC.title" content="The Great War, 1914-1918"/>
  <meta name="DC.creator" content="Lewis H. Beck Center for Electronic Collections & Services"/>
  <meta name="DC.publisher" content="Lewis H. Beck Center for Electronic Collections & Services"/>
  <meta name="DC.subject" content="Poetry"/>
  <meta name="DC.subject" content="Postcards"/>
  <meta name="DC.subject" content="World War I"/>
  <meta name="DC.subject" content="World War, 1914-1918"/>
  <meta name="DC.subject" content="Emory University"/>
  <meta name="DC.description" content="Poetry written between 1914 and 1918 from 50 scarce volumes acquired by Emory University and a collection of some 450 postcards from World War I."/>
  <meta name="DC.type" scheme="DCTERMS.DCMIType" content="text"/>
  <meta name="DC.format" scheme="DCTERMS.IMT" content="text/html"/>
  <meta name="DC.identifier" content="http://beck.library.emory.edu/greatwar/"/>
  <meta name="DC.date" content="2004-10-01"/>

   <title>The Great War: <?= $this->escape($this->title) ?></title>

</head>

<body bgcolor="#5d6a50">    
  
    <?= $this->layout()->content ?>  
 
</body>
</html>	
